(function(){
'use strict';
var POSTS_KEY='viora_tg_posts_v1', PLAN_KEY='viora_tg_plan_v1';
function q(s){return document.querySelector(s);}
function escH(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function toastY(m){try{if(typeof window.toast==='function'){window.toast(m);return;}}catch(e){}}
function lget(k,d){try{var v=JSON.parse(localStorage.getItem(k));return v==null?d:v;}catch(e){return d;}}
function lset(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch(e){try{Object.keys(localStorage).filter(function(x){return x.indexOf('ytc:')===0;}).forEach(function(x){localStorage.removeItem(x);});localStorage.setItem(k,JSON.stringify(v));return true;}catch(e2){return false;}}}
function uid(){return 'p'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);}
function arr(a){return Array.isArray(a)?a:(a?[a]:[]);}
function scoreColor(n){return n>=70?'#7ee0a2':(n>=45?'#ffcf7a':'#ff8fa3');}
function fmtDate(ts){try{return new Date(ts).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});}catch(e){return '';}}
function jsonFrom(t){if(t==null)return null;if(typeof t!=='string')return t;try{return JSON.parse(t);}catch(e){}var i=t.search(/[\[{]/);if(i<0)return null;var open=t[i],close=open==='['?']':'}';var depth=0,inStr=false,esc=false;for(var j=i;j<t.length;j++){var ch=t[j];if(inStr){if(esc)esc=false;else if(ch==='\\')esc=true;else if(ch==='"')inStr=false;continue;}if(ch==='"')inStr=true;else if(ch===open)depth++;else if(ch===close){depth--;if(depth===0){try{return JSON.parse(t.slice(i,j+1));}catch(e){return null;}}}}return null;}
async function aiText(sys,user,max){if(typeof window.callMistralRaw==='function'){return await window.callMistralRaw(sys,user,max||1200);}if(typeof window.tgCallAI==='function'){return await window.tgCallAI([{role:'system',content:sys},{role:'user',content:user}],max||1200);}throw new Error('AI unavailable');}
function pget(){var a=lget(POSTS_KEY,[]);return Array.isArray(a)?a:[];}
function pset(a){lset(POSTS_KEY,a);}
function ptext(p){return (p&&(p.text||p.content))||'';}
function getAn(p){if(!p)return null;if(p.an&&p.an.s)return p.an;if(p.analysis&&p.analysis.s)return p.analysis;var t=ptext(p);try{if(typeof window.tgAnalyzeLocal==='function')return window.tgAnalyzeLocal(t);}catch(e){}return null;}
function pAddOne(text){text=String(text||'').trim();if(!text)return null;var an=null;try{if(typeof window.tgAnalyzeLocal==='function')an=window.tgAnalyzeLocal(text);}catch(e){}var p={id:uid(),text:text,ts:Date.now(),an:an};var a=pget();a.unshift(p);pset(a);return p;}
function pdSplit(t){t=String(t||'').replace(/\r/g,'');var parts;if(/^\s*-{3,}\s*$/m.test(t)){parts=t.split(/^\s*-{3,}\s*$/m);}else{parts=t.split(/\n{2,}/);}return parts.map(function(s){return s.trim();}).filter(function(s){return s.length>0;});}
window.__VP={pget:pget,pset:pset,ptext:ptext,getAn:getAn,escH:escH,arr:arr,scoreColor:scoreColor,jsonFrom:jsonFrom,aiText:aiText};
function postCard(p){var V=window.__VP;var an=V.getAn(p);var sc=an&&an.overall!=null?Math.round(an.overall):null;var col=sc==null?'#5fb0e6':V.scoreColor(sc);var t=V.ptext(p);var snip=V.escH(t.slice(0,120))+(t.length>120?'…':'');var ring=sc==null?'<div class="vp-ring na"><span>—</span></div>':'<div class="vp-ring" style="background:conic-gradient('+col+' '+(sc*3.6)+'deg,rgba(255,255,255,.08) 0)"><span style="color:'+col+'">'+sc+'</span></div>';return '<div class="vp-item" onclick="vpO(\''+p.id+'\')">'+ring+'<div class="vp-item-main"><div class="vp-item-txt">'+snip+'</div><div class="vp-item-meta">'+fmtDate(p.ts)+'</div></div><div class="vp-item-acts"><button title="Совет в чате" onclick="event.stopPropagation();vpAsk(\''+p.id+'\')">💡</button><button title="Удалить" onclick="event.stopPropagation();vpDel(\''+p.id+'\')">🗑</button></div></div>';}
function pdRender(){var V=window.__VP;var a=V.pget();var n=a.length;['#vpCount','#vPostCount'].forEach(function(s){var e=q(s);if(e)e.textContent=n;});var list=q('#vpList');if(list)list.innerHTML=n?a.map(postCard).join(''):'<div class="vp-empty">Пока нет постов. Вставь их в поле выше — Viora разберёт каждый локально, без ИИ.</div>';var info=q('#vpListInfo');if(info)info.textContent=n?('📋 '+n):'';var mini=q('#stgPostList');if(mini)mini.innerHTML=n?a.slice(0,40).map(postCard).join(''):'<div class="stg-empty">Постов пока нет. Нажми «Добавить пост».</div>';}
window.__VP.pdRender=pdRender;
window.vpOpen=function(){var d=q('#vpDrawer');if(!d)return;pdRender();d.classList.add('open');window.vpCount();setTimeout(function(){var ta=q('#vpBulk');if(ta)ta.focus();},140);};
window.vpClose=function(){var d=q('#vpDrawer');if(d)d.classList.remove('open');};
window.vpCount=function(){var ta=q('#vpBulk');var btn=q('#vpAddBtn');if(!ta||!btn)return;var n=pdSplit(ta.value).length;btn.textContent=n>1?('Добавить посты ('+n+')'):(n===1?'Добавить пост':'Добавить посты');btn.disabled=n===0;};
window.vpBulkAdd=function(){var ta=q('#vpBulk');if(!ta)return;var parts=pdSplit(ta.value);if(!parts.length){toastY('Вставь хотя бы один пост');return;}var n=0;parts.forEach(function(t){if(pAddOne(t))n++;});ta.value='';window.vpCount();pdRender();toastY('Добавлено постов: '+n);};
window.vpO=function(id){var V=window.__VP;var p=V.pget().filter(function(x){return x.id===id;})[0];if(!p)return;var an=V.getAn(p);var anHtml=(an&&typeof window.tgRenderAnalysis==='function')?window.tgRenderAnalysis(an):'<div class="vp-empty">Аналитика недоступна</div>';var html='<button class="vp-x" style="position:absolute;top:16px;right:16px" onclick="vpModalClose()">×</button><div class="vp-detail-an">'+anHtml+'</div><div class="vp-detail-txt">'+V.escH(V.ptext(p)).replace(/\n/g,'<br>')+'</div><div class="vp-detail-acts"><button class="vp-add" style="width:auto" onclick="vpAsk(\''+p.id+'\')">💡 Совет Viora в чате</button><button class="vp-del2" onclick="vpDel(\''+p.id+'\',true)">Удалить</button></div>';var card=q('#vpModalCard');if(card)card.innerHTML=html;var m=q('#vpModal');if(m)m.classList.add('open');};
window.vpModalClose=function(){var m=q('#vpModal');if(m)m.classList.remove('open');};
window.vpDel=function(id,fromModal){var V=window.__VP;V.pset(V.pget().filter(function(x){return x.id!==id;}));pdRender();if(fromModal)window.vpModalClose();toastY('Пост удалён');};
window.vpAsk=function(id){var V=window.__VP;var p=V.pget().filter(function(x){return x.id===id;})[0];if(!p)return;window.__VPOSTSEL={id:p.id,text:V.ptext(p)};window.vpModalClose();window.vpClose();try{if(typeof window.tgTab==='function')window.tgTab('chats');}catch(e){}var inp=q('#tgInput');if(inp){inp.value='Глянь мой пост (он у тебя в контексте) — что улучшить и про что написать следующий пост?';if(typeof window.tgAutoGrow==='function')window.tgAutoGrow(inp);}try{if(typeof window.tgSendChat==='function')window.tgSendChat();}catch(e){}};
window.tgStreamBot=function(ans){return new Promise(function(res){ans=String(ans==null?'':ans);var box=q('#stgScrollIn');try{var c=window.tgEnsureChat();c.messages.push({role:'bot',content:ans});if(typeof window.tgSave==='function')window.tgSave();if(typeof window.tgRenderChatList==='function')window.tgRenderChatList();}catch(e){}if(!box){res();return;}var w=box.querySelector('.stg-welcome');if(w)box.innerHTML='';var d=document.createElement('div');d.className='stg-msg bot';d.innerHTML='<div class="ava">'+(window.TG_AVA||'')+'</div><div class="vbwrap" style="flex:1;min-width:0"><div class="body"></div></div>';box.appendChild(d);var body=d.querySelector('.body');var toks=ans.split(/(\s+)/);var i=0,acc='';var speed=ans.length>800?7:15;function md(x){return (typeof window.tgMd==='function')?window.tgMd(x):window.__VP.escH(x);}function fin(){body.innerHTML=md(ans);try{var acts=(typeof window.tgActions==='function')?window.tgActions():'';if(acts)d.querySelector('.vbwrap').insertAdjacentHTML('beforeend',acts);}catch(e){}if(typeof window.tgScrollBottom==='function')window.tgScrollBottom();res();}function step(){if(i>=toks.length){fin();return;}var k=0;while(i<toks.length&&k<3){acc+=toks[i];i++;k++;}body.innerHTML=md(acc)+'<span class="stg-caret"></span>';if((i%8)===0&&typeof window.tgScrollBottom==='function')window.tgScrollBottom();setTimeout(step,speed);}step();});};
window.tgSendChat=async function(){if(window.TG_SENDING)return;var inp=q('#tgInput');if(!inp)return;var qv=inp.value.trim();if(!qv)return;inp.value='';if(typeof window.tgAutoGrow==='function')window.tgAutoGrow(inp);try{window.tgEnsureChat();}catch(e){}window.tgAddMessage('user',{content:qv});var mode=window.TG_MODE;var isPost=(mode==='analyze')||(mode==='auto'&&(typeof window.tgDetectPost==='function'&&window.tgDetectPost(qv)));if(isPost){try{var an0=window.tgAnalyzeLocal(qv);window.tgAddMessage('bot',{html:window.tgRenderAnalysis(an0)});}catch(e){}}window.TG_SENDING=true;if(typeof window.tgSetSend==='function')window.tgSetSend(true);if(typeof window.tgTyping==='function')window.tgTyping();try{var sys=window.VIORA_TG_SYS(mode,isPost);var c=window.tgCur();var hist=c.messages.filter(function(x){return x.content;}).map(function(x){return {role:x.role==='bot'?'assistant':'user',content:x.content};}).slice(-8);var msgs=[{role:'system',content:sys}].concat(hist);var ans=await window.tgCallAI(msgs,isPost?1300:420);if(typeof window.tgHideTyping==='function')window.tgHideTyping();await window.tgStreamBot(ans);try{window.__VPOSTSEL=null;}catch(e){}}catch(e){if(typeof window.tgHideTyping==='function')window.tgHideTyping();window.tgAddMessage('bot',{content:'⚠️ Viora AI сейчас недоступна — попробуй ещё раз через пару секунд.'});}window.TG_SENDING=false;if(typeof window.tgSetSend==='function')window.tgSetSend(false);var i2=q('#tgInput');if(i2)i2.focus();};
window.buildTgContext=function(){var V=window.__VP;var base='';try{if(typeof STATE!=='undefined'&&STATE&&STATE.channel&&STATE.channel.title){var c=STATE.channel;base='У пользователя уже разобран YouTube-канал "'+(c.title||'')+'" (подписчиков: '+(c.subs||'?')+'). Предлагай, как переливать аудиторию в Telegram и какие ролики/Shorts снять.';}else{base='YouTube-аудит пока не сделан.';}}catch(e){base='YouTube-аудит пока не сделан.';}try{var _pc=(window.vGetProfileChannels?window.vGetProfileChannels():[]);if(_pc.length){var _yt=_pc.filter(function(c){return c.type==='yt';}).map(function(c){return c.title||c.handle;});var _tg=_pc.filter(function(c){return c.type==='tg';}).map(function(c){return c.title||c.handle;});var _own='';if(_yt.length)_own+=' Свой YouTube-канал автора: '+_yt.join(', ')+'.';if(_tg.length)_own+=' Свой Telegram-канал автора: '+_tg.join(', ')+'.';if(_own)base+=' Каналы автора из профиля:'+_own+' Привязывай советы и кросс-промо именно к этим каналам автора.';}}catch(e){}var extra='';try{var a=V.pget();if(a.length){var top=a.slice(0,8).map(function(p){var an=V.getAn(p);var sc=an&&an.overall!=null?Math.round(an.overall):'—';return '• ['+sc+'/100] '+V.ptext(p).replace(/\s+/g,' ').slice(0,80);}).join('\n');extra+='\n\nЗагруженные посты пользователя ('+a.length+'):\n'+top;}}catch(e){}try{var sel=window.__VPOSTSEL;if(sel&&sel.text){extra+='\n\nПользователь спрашивает про конкретный пост:\n"""\n'+String(sel.text).slice(0,1500)+'\n"""\nДай разбор именно по нему и предложи 2-3 темы для следующих постов.';}}catch(e){}return base+extra;};
function dashData(){var au=[],id=[];try{if(typeof window.load==='function'&&window.KA)au=window.load(window.KA)||[];}catch(e){}try{if(typeof window.load==='function'&&window.KI)id=window.load(window.KI)||[];}catch(e){}var pl=lget(PLAN_KEY,[]);if(!Array.isArray(pl))pl=[];return {audits:au,ideas:id,posts:window.__VP.pget(),plan:pl};}
function renderDash(){var V=window.__VP;var d=dashData();var au=d.audits,id=d.ideas,po=d.posts,pl=d.plan;var avgPost=po.length?Math.round(po.reduce(function(a,p){var an=V.getAn(p);return a+((an&&an.overall)||0);},0)/po.length):0;var kpis=[['Разборов канала',au.length],['Поисков идей',id.length],['Постов в студии',po.length],['Ср. балл постов',avgPost||'—'],['Дней в плане',pl.length]];var kp='<div class="vd-kpis">'+kpis.map(function(k){return '<div class="vd-kpi"><div class="n">'+k[1]+'</div><div class="l">'+k[0]+'</div></div>';}).join('')+'</div>';var prog='';if(au.length){var asc=au.slice().reverse();var bars=asc.map(function(a){var s=Math.max(0,Math.min(100,a.score||0));return '<i style="height:'+Math.max(6,s)+'%" title="'+V.escH(a.title||'')+': '+Math.round(s)+'"></i>';}).join('');var latest=au[0];var delta='';if(au.length>=2){var dl=Math.round((au[0].score||0)-(au[1].score||0));delta='<div class="s" style="color:'+(dl>=0?'#7ee0a2':'#ff8fa3')+'">'+(dl>=0?'▲ +':'▼ ')+dl+'</div>';}prog='<div class="vd-sec"><div class="vd-sec-h">📈 Прогресс канала</div><div class="vd-row"><div class="t"><b>'+V.escH(latest.title||'Канал')+'</b>'+(latest.niche?(' · '+V.escH(latest.niche)):'')+'</div><div class="s" style="color:'+V.scoreColor(latest.score||0)+'">'+Math.round(latest.score||0)+'/100</div>'+delta+'</div><div class="vd-spark">'+bars+'</div></div>';}else{prog='<div class="vd-sec"><div class="vd-sec-h">📈 Прогресс канала</div><div class="vd-empty">Сделай аудит канала во вкладке YouTube — здесь появится динамика.</div></div>';}var auList=au.length?au.map(function(a){return '<div class="vd-row"><div class="t">'+V.escH(a.title||'Канал')+'</div><div class="s" style="color:'+V.scoreColor(a.score||0)+'">'+Math.round(a.score||0)+'</div><div class="m">'+fmtDate(a.ts)+'</div></div>';}).join(''):'<div class="vd-empty">Разборов пока нет.</div>';var idList=id.length?id.map(function(x){return '<div class="vd-row"><div class="t">'+V.escH(x.query||'—')+'</div><div class="m">'+(x.count||0)+' видео · x'+(Number(x.avgMult)||0).toFixed(1)+'</div><div class="m">'+fmtDate(x.ts)+'</div></div>';}).join(''):'<div class="vd-empty">Поисков идей пока нет.</div>';var two='<div class="vd-twocol"><div class="vd-sec"><div class="vd-sec-h">🗂 История разборов</div>'+auList+'</div><div class="vd-sec"><div class="vd-sec-h">💡 История идей</div>'+idList+'</div></div>';var topPosts='';if(po.length){var sorted=po.slice().sort(function(a,b){return ((V.getAn(b)||{}).overall||0)-((V.getAn(a)||{}).overall||0);}).slice(0,5);topPosts='<div class="vd-sec"><div class="vd-sec-h">🏆 Сильнейшие посты</div>'+sorted.map(function(p){var an=V.getAn(p);var s=an&&an.overall!=null?Math.round(an.overall):'—';return '<div class="vd-row"><div class="s" style="color:'+(an?V.scoreColor(an.overall):'#888')+'">'+s+'</div><div class="t">'+V.escH(V.ptext(p).replace(/\s+/g,' ').slice(0,90))+'</div></div>';}).join('')+'</div>';}return '<div class="vov-pad">'+kp+prog+two+topPosts+'</div>';}
window.vDashOpen=function(){var b=q('#vDashBody');if(b)b.innerHTML=renderDash();var m=q('#vDash');if(m)m.classList.add('open');};
window.vDashClose=function(){var m=q('#vDash');if(m)m.classList.remove('open');};
var SCRIPT_SYS='Ты — Viora AI, сценарист роликов YouTube с задачей переливать аудиторию в Telegram. Методика: 1) ХУК в первые 1-3 сек (боль/интрига/шок/обещание результата), без приветствий; 2) быстрое погружение без воды; 3) удержание — каждые 15-25 сек новый крючок; 4) явная ценность; 5) органичный призыв в Telegram за конкретным бонусом. Конкретно, без клише. Верни СТРОГО валидный JSON без markdown по схеме: {"title_ideas":["..."],"hooks":["..."],"intro":"...","beats":[{"time":"0:00-0:15","label":"...","script":"..."}],"climax":"...","tg_cta":"...","pinned":"...","thumbnail":{"concept":"...","text":["..."]},"shooting":["..."]}. Для Shorts 4-6 beats по 5-15 сек; для длинного 6-9 beats с таймкодами.';
function renderScript(d){var V=window.__VP;var titles=V.arr(d.title_ideas).map(function(t){return '<span class="vsc-pill">'+V.escH(t)+'</span>';}).join('');var hooks=V.arr(d.hooks).map(function(h,i){return '<div class="vsc-beat"><div class="tm">Хук '+(i+1)+'</div><div class="bd">'+V.escH(h)+'</div></div>';}).join('');var beats=V.arr(d.beats).map(function(b){return '<div class="vsc-beat"><div class="tm">'+V.escH(b.time||'')+'</div><div class="bd"><b>'+V.escH(b.label||'')+'</b><br>'+V.escH(b.script||'')+'</div></div>';}).join('');var thumb=d.thumbnail||{};var thumbTxt=V.arr(thumb.text).map(function(t){return '<span class="vsc-pill">'+V.escH(t)+'</span>';}).join('');var shoot=V.arr(d.shooting).map(function(s){return '<div class="vsc-beat"><div class="tm">🎥</div><div class="bd">'+V.escH(s)+'</div></div>';}).join('');var o='';if(titles)o+='<div class="vsc-block"><h4>🎯 Заголовки</h4>'+titles+'</div>';if(hooks)o+='<div class="vsc-block"><h4>🪝 Хуки (первые секунды)</h4>'+hooks+'</div>';if(d.intro)o+='<div class="vsc-block"><h4>🚀 Вступление</h4><div style="font-size:13.5px;line-height:1.6;color:#dfe3e7">'+V.escH(d.intro)+'</div></div>';if(beats)o+='<div class="vsc-block"><h4>🎬 Сценарий по блокам</h4>'+beats+'</div>';if(d.climax)o+='<div class="vsc-block"><h4>💥 Кульминация</h4><div style="font-size:13.5px;line-height:1.6;color:#dfe3e7">'+V.escH(d.climax)+'</div></div>';if(d.tg_cta||d.pinned)o+='<div class="vsc-block vsc-cta"><h4>✈️ Перелив в Telegram</h4>'+(d.tg_cta?'<div style="font-size:13.5px;line-height:1.6;color:#eaf4fb"><b>В ролике:</b> '+V.escH(d.tg_cta)+'</div>':'')+(d.pinned?'<div style="font-size:13.5px;line-height:1.6;color:#eaf4fb;margin-top:8px"><b>В Telegram:</b> '+V.escH(d.pinned)+'</div>':'')+'</div>';if(thumb.concept||thumbTxt)o+='<div class="vsc-block"><h4>🖼 Обложка</h4>'+(thumb.concept?'<div style="font-size:13.5px;line-height:1.6;color:#dfe3e7;margin-bottom:8px">'+V.escH(thumb.concept)+'</div>':'')+thumbTxt+'</div>';if(shoot)o+='<div class="vsc-block"><h4>🎥 Подсказки по съёмке</h4>'+shoot+'</div>';o+='<div class="vsc-tools"><button class="vsc-tool" onclick="vScriptCopy()">📋 Скопировать</button><button class="vsc-tool" onclick="vScriptToChat()">💬 Доработать в чате Viora</button></div>';return o;}
window.vScriptOpen=function(){var m=q('#vScript');if(m)m.classList.add('open');var o=q('#vScriptOut');if(o&&!o.dataset.filled)o.innerHTML='<div class="vsc-hint">Заполни тему и нажми «Сгенерировать». Viora соберёт сценарий по методике: цепляющий хук в первые секунды, удержание и плавный перелив в Telegram.</div>';setTimeout(function(){var t=q('#vsTopic');if(t)t.focus();},140);};
window.vScriptClose=function(){var m=q('#vScript');if(m)m.classList.remove('open');};
window.vScriptRun=async function(){var V=window.__VP;var topic=((q('#vsTopic')||{}).value||'').trim();if(!topic){toastY('Напиши тему ролика');return;}var fmt=((q('#vsFormat')||{}).value)||'Shorts';var goal=((q('#vsGoal')||{}).value||'').trim();var btn=q('#vsRunBtn');var o=q('#vScriptOut');if(btn){btn.disabled=true;btn.dataset.t=btn.textContent;btn.textContent='Генерирую…';}if(o){o.dataset.filled='1';o.innerHTML='<div class="vsc-load"><div class="vsc-spin"></div>Viora пишет сценарий под перелив в Telegram…</div>';}var chTitle='';try{if(typeof STATE!=='undefined'&&STATE&&STATE.channel)chTitle=STATE.channel.title||'';}catch(e){}var user='ФОРМАТ: '+fmt+'\nТЕМА: '+topic+(goal?('\nБОНУС ДЛЯ ПЕРЕЛИВА: '+goal):'')+(chTitle?('\nКАНАЛ: '+chTitle):'')+'\nВерни СТРОГО валидный JSON по схеме.';try{var raw=await V.aiText(SCRIPT_SYS,user,1800);var data=V.jsonFrom(raw);if(!data){if(o)o.innerHTML='<div class="vsc-hint">Не удалось разобрать ответ. Попробуй ещё раз.</div>';}else{window.__vLastScript=data;if(o)o.innerHTML=renderScript(data);}}catch(e){if(o)o.innerHTML='<div class="vsc-hint">Viora недоступна — попробуй через пару секунд.</div>';}if(btn){btn.disabled=false;btn.textContent=btn.dataset.t||'Сгенерировать сценарий';}};
window.vScriptCopy=function(){var V=window.__VP;var d=window.__vLastScript;if(!d)return;var L=[];function ad(t){L.push(t);}if(d.title_ideas)ad('ЗАГОЛОВКИ:\n- '+V.arr(d.title_ideas).join('\n- '));if(d.hooks)ad('\nХУКИ:\n- '+V.arr(d.hooks).join('\n- '));if(d.intro)ad('\nВСТУПЛЕНИЕ:\n'+d.intro);if(d.beats)ad('\nСЦЕНАРИЙ:\n'+V.arr(d.beats).map(function(b){return (b.time||'')+' — '+(b.label||'')+': '+(b.script||'');}).join('\n'));if(d.climax)ad('\nКУЛЬМИНАЦИЯ:\n'+d.climax);if(d.tg_cta)ad('\nПРИЗЫВ В TELEGRAM:\n'+d.tg_cta);if(d.pinned)ad('\nЗАКРЕП:\n'+d.pinned);if(d.thumbnail)ad('\nОБЛОЖКА:\n'+(d.thumbnail.concept||'')+(d.thumbnail.text?('\nТекст: '+V.arr(d.thumbnail.text).join(' / ')):''));if(d.shooting)ad('\nСЪЁМКА:\n- '+V.arr(d.shooting).join('\n- '));try{navigator.clipboard.writeText(L.join('\n'));toastY('Сценарий скопирован');}catch(e){}};
window.vScriptToChat=function(){var V=window.__VP;var d=window.__vLastScript;if(!d)return;window.vScriptClose();try{if(typeof window.tgTab==='function')window.tgTab('chats');}catch(e){}var inp=q('#tgInput');if(inp){var topic=V.arr(d.title_ideas)[0]||'';inp.value='Доработай этот сценарий'+(topic?(' («'+topic+'»)'):'')+': добавь хуков и усиль призыв в Telegram.';if(typeof window.tgAutoGrow==='function')window.tgAutoGrow(inp);}toastY('Открыл чат Viora');};
window.postAdd=function(){window.vpOpen();};window.renderPosts=function(){window.__VP.pdRender();};window.postOpen=function(id){window.vpO(id);};window.postDel=function(id){window.vpDel(id);};window.postAsk=function(id){window.vpAsk(id);};
var CSS=`
.stg-caret{display:inline-block;width:7px;height:1.02em;background:linear-gradient(180deg,#5fb0e6,#2aabee);border-radius:2px;margin-left:2px;vertical-align:text-bottom;animation:vcaret .8s steps(2) infinite}
@keyframes vcaret{0%,100%{opacity:1}50%{opacity:0}}
.vp-drawer{position:fixed;inset:0;z-index:9000;pointer-events:none}
.vp-drawer .vp-scrim{position:absolute;inset:0;background:rgba(4,7,10,.6);opacity:0;transition:.3s;backdrop-filter:blur(2px)}
.vp-drawer.open{pointer-events:auto}.vp-drawer.open .vp-scrim{opacity:1}
.vp-panel{position:absolute;top:0;right:0;height:100%;width:460px;max-width:92vw;background:linear-gradient(180deg,#16191d,#101316);border-left:1px solid rgba(95,176,230,.18);box-shadow:-30px 0 80px rgba(0,0,0,.5);transform:translateX(105%);transition:transform .34s cubic-bezier(.22,1,.36,1);display:flex;flex-direction:column}
.vp-drawer.open .vp-panel{transform:none}
.vp-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.06)}
.vp-title{font-family:'Onest',Inter,sans-serif;font-weight:600;font-size:17px;display:flex;align-items:center;gap:10px}
.vp-badge{background:linear-gradient(135deg,#2aabee,#229ed9);color:#fff;font-size:12px;padding:2px 9px;border-radius:20px;font-weight:600}
.vp-x{background:rgba(255,255,255,.06);border:none;color:#9aa3ad;width:32px;height:32px;border-radius:9px;font-size:19px;cursor:pointer;transition:.2s;line-height:1}
.vp-x:hover{background:rgba(255,90,110,.18);color:#fff}
.vp-body{flex:1;overflow-y:auto;padding:18px 20px;display:flex;flex-direction:column;gap:18px}
.vp-bulk{background:rgba(95,176,230,.06);border:1px solid rgba(95,176,230,.16);border-radius:16px;padding:16px}
.vp-bulk-h{font-family:'Onest',Inter,sans-serif;font-weight:600;font-size:14px;color:#9fd4ff;margin-bottom:6px}
.vp-bulk-sub{font-size:12.5px;color:#8b949e;line-height:1.5;margin-bottom:12px}
.vp-ta{width:100%;min-height:150px;resize:vertical;background:rgba(0,0,0,.3);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:12px 14px;color:#e8eaed;font-size:14px;line-height:1.6;font-family:inherit;box-sizing:border-box}
.vp-ta:focus{outline:none;border-color:#2aabee;box-shadow:0 0 0 3px rgba(42,171,238,.15)}
.vp-add{margin-top:12px;width:100%;background:linear-gradient(135deg,#2aabee,#229ed9);border:none;color:#fff;font-weight:600;font-size:14px;padding:12px;border-radius:11px;cursor:pointer;transition:.2s;font-family:'Onest',Inter,sans-serif}
.vp-add:hover{filter:brightness(1.08);transform:translateY(-1px)}.vp-add:disabled{opacity:.5;cursor:default;transform:none}
.vp-list-h{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#7a828c;font-weight:600}
.vp-list{display:flex;flex-direction:column;gap:10px}
.vp-item{display:flex;align-items:center;gap:12px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06);border-radius:13px;padding:11px 13px;cursor:pointer;transition:.18s}
.vp-item:hover{background:rgba(95,176,230,.08);border-color:rgba(95,176,230,.25);transform:translateY(-1px)}
.vp-ring{flex:0 0 auto;width:44px;height:44px;border-radius:50%;display:grid;place-items:center;position:relative}
.vp-ring::after{content:'';position:absolute;inset:4px;background:#15181c;border-radius:50%}
.vp-ring span{position:relative;z-index:1;font-size:13px;font-weight:700;font-family:'Onest',Inter,sans-serif}
.vp-ring.na{background:rgba(255,255,255,.06)}.vp-ring.na span{color:#6b7178}
.vp-item-main{flex:1;min-width:0}
.vp-item-txt{font-size:13.5px;color:#dfe3e7;line-height:1.4;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.vp-item-meta{font-size:11.5px;color:#7a828c;margin-top:3px}
.vp-item-acts{display:flex;gap:4px;flex:0 0 auto}
.vp-item-acts button{background:rgba(255,255,255,.05);border:none;width:30px;height:30px;border-radius:8px;cursor:pointer;font-size:14px;transition:.18s}
.vp-item-acts button:hover{background:rgba(255,255,255,.14)}
.vp-empty,.stg-empty{color:#7a828c;font-size:13px;text-align:center;padding:22px 10px;line-height:1.6}
.vp-modal,.vov{position:fixed;inset:0;z-index:9100;display:none;align-items:center;justify-content:center;padding:24px}
.vp-modal.open,.vov.open{display:flex}
.vp-modal .vp-scrim,.vov-scrim{position:absolute;inset:0;background:rgba(4,7,10,.66);backdrop-filter:blur(3px)}
.vp-card{position:relative;z-index:1;width:560px;max-width:94vw;max-height:88vh;overflow-y:auto;background:linear-gradient(180deg,#181b1f,#111418);border:1px solid rgba(255,255,255,.09);border-radius:20px;padding:22px;box-shadow:0 30px 90px rgba(0,0,0,.6);animation:vpop .28s cubic-bezier(.22,1,.36,1)}
@keyframes vpop{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}
.vp-detail-txt{margin-top:16px;background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:14px;font-size:14px;line-height:1.6;color:#dfe3e7}
.vp-detail-acts{margin-top:16px;display:flex;gap:10px;flex-wrap:wrap}
.vp-del2{background:rgba(255,90,110,.12);border:1px solid rgba(255,90,110,.3);color:#ff9aa8;border-radius:11px;padding:11px 16px;cursor:pointer;font-size:13.5px}
.vov-card{position:relative;z-index:1;width:940px;max-width:96vw;max-height:90vh;overflow-y:auto;background:linear-gradient(180deg,#15181c,#0e1115);border:1px solid rgba(255,255,255,.09);border-radius:22px;box-shadow:0 40px 110px rgba(0,0,0,.65);animation:vpop .3s cubic-bezier(.22,1,.36,1)}
.vov-card>header{position:sticky;top:0;background:#16191d;display:flex;align-items:center;justify-content:space-between;padding:20px 24px;font-family:'Onest',Inter,sans-serif;font-weight:600;font-size:19px;z-index:2;border-bottom:1px solid rgba(255,255,255,.06)}
.vov-pad{padding:20px 24px 26px}
.vd-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:22px}
.vd-kpi{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.07);border-radius:15px;padding:15px;text-align:center}
.vd-kpi .n{font-family:'Onest',Inter,sans-serif;font-size:26px;font-weight:700;background:linear-gradient(135deg,#5fb0e6,#2aabee);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}
.vd-kpi .l{font-size:11.5px;color:#8b949e;margin-top:4px}
.vd-sec{margin-bottom:22px}
.vd-sec-h{font-family:'Onest',Inter,sans-serif;font-size:14px;color:#9fd4ff;font-weight:600;margin-bottom:12px;display:flex;align-items:center;gap:8px}
.vd-row{display:flex;align-items:center;gap:12px;padding:11px 14px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06);border-radius:12px;margin-bottom:8px}
.vd-row .t{flex:1;min-width:0;font-size:13.5px;color:#e3e6ea;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.vd-row .s{font-family:'Onest',Inter,sans-serif;font-weight:700;font-size:14px}
.vd-row .m{font-size:11.5px;color:#7a828c;flex:0 0 auto}
.vd-spark{display:flex;align-items:flex-end;gap:5px;height:60px;padding:10px 0}
.vd-spark i{flex:1;background:linear-gradient(180deg,#2aabee,#1a6fa0);border-radius:4px 4px 0 0;min-height:4px}
.vd-twocol{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.vd-empty{color:#7a828c;font-size:13px;padding:14px;text-align:center;background:rgba(255,255,255,.02);border-radius:12px}
.vsc-form{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:20px 24px 8px}
.vsc-field{display:flex;flex-direction:column;gap:6px}
.vsc-field.full{grid-column:1/-1}
.vsc-field label{font-size:12px;color:#9aa3ad;font-weight:600}
.vsc-field input,.vsc-field select,.vsc-field textarea{background:rgba(0,0,0,.3);border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:10px 12px;color:#e8eaed;font-size:14px;font-family:inherit;box-sizing:border-box}
.vsc-field textarea{min-height:70px;resize:vertical}
.vsc-field input:focus,.vsc-field select:focus,.vsc-field textarea:focus{outline:none;border-color:#2aabee}
.vsc-run{grid-column:1/-1;background:linear-gradient(135deg,#2aabee,#229ed9);border:none;color:#fff;font-weight:600;padding:13px;border-radius:12px;cursor:pointer;font-family:'Onest',Inter,sans-serif;font-size:14.5px;transition:.2s}
.vsc-run:hover{filter:brightness(1.08);transform:translateY(-1px)}.vsc-run:disabled{opacity:.6}
.vsc-out{padding:8px 24px 26px}
.vsc-hint{color:#8b949e;font-size:13.5px;line-height:1.7;background:rgba(95,176,230,.05);border:1px solid rgba(95,176,230,.14);border-radius:14px;padding:18px}
.vsc-load{display:flex;align-items:center;gap:12px;color:#9fd4ff;font-size:14px;padding:24px}
.vsc-spin{width:22px;height:22px;border:3px solid rgba(95,176,230,.2);border-top-color:#2aabee;border-radius:50%;animation:vspin .8s linear infinite}
@keyframes vspin{to{transform:rotate(360deg)}}
.vsc-block{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.07);border-radius:15px;padding:16px 18px;margin-bottom:14px}
.vsc-block h4{font-family:'Onest',Inter,sans-serif;font-size:13.5px;color:#9fd4ff;margin:0 0 10px;display:flex;align-items:center;gap:8px}
.vsc-pill{display:inline-block;background:rgba(42,171,238,.12);border:1px solid rgba(42,171,238,.25);color:#bfe3ff;padding:6px 11px;border-radius:9px;font-size:13px;margin:0 6px 6px 0}
.vsc-beat{display:flex;gap:12px;padding:9px 0;border-bottom:1px dashed rgba(255,255,255,.07)}
.vsc-beat:last-child{border-bottom:none}
.vsc-beat .tm{flex:0 0 auto;font-family:'Onest',Inter,sans-serif;font-size:12px;color:#7fd0ff;min-width:78px}
.vsc-beat .bd{flex:1;font-size:13.5px;line-height:1.55;color:#dfe3e7}.vsc-beat .bd b{color:#fff}
.vsc-cta{background:linear-gradient(135deg,rgba(42,171,238,.14),rgba(34,158,217,.05));border-color:rgba(42,171,238,.3)}
.vsc-tools{display:flex;gap:10px;margin-top:8px;flex-wrap:wrap}
.vsc-tool{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);color:#dfe3e7;border-radius:10px;padding:10px 15px;cursor:pointer;font-size:13px;transition:.18s}
.vsc-tool:hover{background:rgba(255,255,255,.13)}
.v-hero-btns{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:14px 0 0}
.v-hero-btn{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.12);color:#e8eaed;border-radius:11px;padding:10px 16px;cursor:pointer;font-size:13.5px;transition:.2s;font-family:'Onest',Inter,sans-serif}
.v-hero-btn:hover{background:rgba(95,176,230,.14);border-color:rgba(95,176,230,.3);transform:translateY(-1px)}
@media(max-width:860px){.vp-panel{width:100%;max-width:100%}.vd-kpis{grid-template-columns:repeat(2,1fr)}.vd-twocol,.vsc-form{grid-template-columns:1fr}.vov-card{border-radius:16px}}
`;
var DRAWER_HTML='<div id="vpDrawer" class="vp-drawer"><div class="vp-scrim" onclick="vpClose()"></div><aside class="vp-panel"><header class="vp-head"><div class="vp-title">📝 Мои посты <span class="vp-badge" id="vpCount">0</span></div><button class="vp-x" onclick="vpClose()">×</button></header><div class="vp-body"><div class="vp-bulk"><div class="vp-bulk-h">⚡ Массовое добавление</div><div class="vp-bulk-sub">Вставь до 20–30 постов сразу. Разделяй их строкой <b>---</b> или пустой строкой — Viora разберёт каждый локально, без ИИ.</div><textarea id="vpBulk" class="vp-ta" placeholder="Вставь сюда свои Telegram-посты…&#10;&#10;---&#10;&#10;Следующий пост…" oninput="vpCount()"></textarea><button class="vp-add" id="vpAddBtn" onclick="vpBulkAdd()" disabled>Добавить посты</button></div><div class="vp-list-h">Сохранённые посты <span id="vpListInfo"></span></div><div id="vpList" class="vp-list"></div></div></aside></div>';
var MODAL_HTML='<div id="vpModal" class="vp-modal"><div class="vp-scrim" onclick="vpModalClose()"></div><div class="vp-card" id="vpModalCard"></div></div>';
var DASH_HTML='<div id="vDash" class="vov"><div class="vov-scrim" onclick="vDashClose()"></div><div class="vov-card"><header><span>📊 Дашборд студии</span><button class="vp-x" onclick="vDashClose()">×</button></header><div id="vDashBody"></div></div></div>';
var SCRIPT_HTML='<div id="vScript" class="vov"><div class="vov-scrim" onclick="vScriptClose()"></div><div class="vov-card"><header><span>🎬 Генератор сценариев</span><button class="vp-x" onclick="vScriptClose()">×</button></header><div class="vsc-form"><div class="vsc-field full"><label>Тема / идея ролика</label><textarea id="vsTopic" placeholder="Например: как новичку собрать первый ПК и не переплатить"></textarea></div><div class="vsc-field"><label>Формат</label><select id="vsFormat"><option>Shorts</option><option>Длинный ролик</option></select></div><div class="vsc-field"><label>Что предложить в Telegram</label><input id="vsGoal" placeholder="чек-лист / разбор / закрытый пост"></div><button class="vsc-run" id="vsRunBtn" onclick="vScriptRun()">✨ Сгенерировать сценарий</button></div><div id="vScriptOut" class="vsc-out"></div></div></div>';
function injectAll(){if(!q('#vp45css')){var st=document.createElement('style');st.id='vp45css';st.textContent=CSS;document.head.appendChild(st);}if(!q('#vpDrawer')){var wrap=document.createElement('div');wrap.innerHTML=DRAWER_HTML+MODAL_HTML+DASH_HTML+SCRIPT_HTML;while(wrap.firstChild){document.body.appendChild(wrap.firstChild);}}var foot=q('.stg-side-foot');if(foot&&!q('#vDashFootBtn')){foot.insertAdjacentHTML('beforeend','<button id="vDashFootBtn" class="stg-foot-btn" onclick="vDashOpen()">📊 Дашборд студии</button>');}var ms=q('#modeSwitch');if(ms&&!q('#vHeroBtns')){var hw=document.createElement('div');hw.id='vHeroBtns';hw.className='v-hero-btns';hw.innerHTML='<button class="v-hero-btn" onclick="vDashOpen()">📊 Дашборд студии</button><button class="v-hero-btn" onclick="vScriptOpen()">🎬 Генератор сценариев</button>';ms.parentNode.insertBefore(hw,ms.nextSibling);}try{window.__VP.pdRender();}catch(e){}}
function boot(){try{injectAll();}catch(e){}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',boot);}else{boot();}
setTimeout(boot,700);setTimeout(boot,1800);
document.addEventListener('keydown',function(e){if(e.key==='Escape'){window.vpClose();window.vpModalClose();window.vDashClose&&window.vDashClose();window.vScriptClose&&window.vScriptClose();}});
})();
