var NL=String.fromCharCode(10);
function _x5id(id){return document.getElementById(id);}
function _x5esc(s){ if(typeof _esc==='function')return _esc(s); return (''+(s==null?'':s)).replace(/[&<>"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'})[c];}); }
function _x5toast(m,i){ try{ if(typeof toast==='function')toast(m,i); }catch(e){} }
function _x5copy(el,txt){ try{ if(typeof copyText==='function'){copyText(el,txt);return;} if(navigator.clipboard)navigator.clipboard.writeText(txt); }catch(e){} }
function _x5S(){ return (typeof STATE!=='undefined'&&STATE)?STATE:{}; }
function _x5lget(k,d){ try{ if(typeof lget==='function')return lget(k,d); var v=localStorage.getItem(k); return v?JSON.parse(v):d; }catch(e){return d;} }
function _x5lset(k,v){ try{ if(typeof lset==='function'){lset(k,v);return;} localStorage.setItem(k,JSON.stringify(v)); }catch(e){} }
function _x5num(n){ try{ if(typeof nfmt==='function')return nfmt(n); }catch(e){} n=+n||0; var a=Math.abs(n),s=n<0?'-':''; return a>=1e6?(s+(a/1e6).toFixed(1)+'M'):a>=1e3?(s+(a/1e3).toFixed(1)+'K'):String(Math.round(n)); }
function _x5chKey(){ var c=_x5S().channel||{}; return 'viora_wk_'+(c.id||c.handle||c.title||'anon'); }
function _x5ctx(){ var s=_x5S(),c=s.channel||{},ai=s.ai||{},sig=s.signals||{}; var L=[]; L.push('Канал: '+(c.title||'без названия')+(c.handle?(' '+c.handle):'')); if(c.subs!=null)L.push('Подписчиков: '+c.subs); if(s.primaryNiche)L.push('Ниша: '+s.primaryNiche); if(ai.main_leak)L.push('Главная утечка роста: '+ai.main_leak); if(ai.hit_formula&&ai.hit_formula.length)L.push('Что у канала залетает: '+ai.hit_formula.slice(0,2).join('; ')); if(sig&&sig.bestWindow&&sig.bestWindow.day)L.push('Лучшее окно публикации: '+sig.bestWindow.day+' '+(sig.bestWindow.hourRange||'')); return L.join(NL); }
async function fnlBuild(){ var out=_x5id('fnlOut'); if(!out)return; if(!_x5S().channel){ out.innerHTML='<div class="muted">Сначала проанализируй канал на главном экране.</div>'; return; } out.innerHTML='<div class="x5-load"><span class="loader-ring"></span> Продюсер проектирует воронку под твой канал…</div>'; var sys='Ты продюсер по росту. Строишь воронку из YouTube в Telegram. YouTube это охват и новые зрители, Telegram это закрытый клуб для лояльных: бонусы, бэкстейдж, ранний доступ, личное общение. Отвечай ТОЛЬКО валидным JSON без markdown и пояснений. Структура: {"idea":"суть связки в 1-2 предложениях","videos":[{"type":"ролик или shorts","title":"идея видео для перелива","why":"его роль в воронке"}],"leadMagnet":{"name":"название лид-магнита","what":"что внутри","how":"как выдаём за подписку"},"pinned":"текст закреплённого поста в Telegram","ytDesc":"строка под ролик со ссылкой и призывом перейти в Telegram","endCta":"фраза-призыв в конце ролика","week":["шаг","шаг","шаг","шаг"]}. Поле videos: 3-4 элемента. Всё строго под нишу и боли канала, конкретно, по-русски, без воды.'; var user='Построй воронку под этот канал.'+NL+'КОНТЕКСТ:'+NL+_x5ctx()+NL+NL+'Лид-магнит должен реально хотеться этой аудитории. Видео должны естественно вести в Telegram.'; try{ var kb=(typeof kbFor==='function')?kbFor('telegram'):''; var d=await callMistralRaw(sys+(kb?(NL+NL+kb):''), user, 1900); _x5renderFunnel(d); }catch(e){ out.innerHTML='<div class="muted">Не удалось собрать воронку, попробуй ещё раз через пару секунд.</div>'; } }
function _x5renderFunnel(d){ var out=_x5id('fnlOut'); if(!out)return; d=d||{}; var H=''; if(d.idea)H+='<div class="fnl-idea">'+_x5esc(d.idea)+'</div>'; if(Array.isArray(d.videos)&&d.videos.length){ H+='<div class="fnl-block"><div class="fb-h">🎬 Видео для перелива аудитории</div><div class="fnl-vids">'; d.videos.forEach(function(v){ v=v||{}; H+='<div class="fnl-vid"><span class="fv-tag">'+_x5esc(v.type||'ролик')+'</span><div class="fv-t">'+_x5esc(v.title||'')+'</div><div class="fv-w">'+_x5esc(v.why||'')+'</div></div>'; }); H+='</div></div>'; } if(d.leadMagnet){ var lm=d.leadMagnet; H+='<div class="fnl-block"><div class="fb-h">🧲 Лид-магнит за подписку</div><div class="fnl-lm"><b>'+_x5esc(lm.name||'')+'</b><div>'+_x5esc(lm.what||'')+'</div><div class="fv-w">Как выдаём: '+_x5esc(lm.how||'')+'</div></div></div>'; } H+=_x5copyBlock('📌 Закреплённый пост в Telegram', d.pinned); H+=_x5copyBlock('🔗 В описании под роликом', d.ytDesc); H+=_x5copyBlock('🎤 Призыв в конце ролика', d.endCta); if(Array.isArray(d.week)&&d.week.length){ H+='<div class="fnl-block"><div class="fb-h">🚀 С чего начать</div><ol class="fnl-steps">'; d.week.forEach(function(s){ H+='<li>'+_x5esc(s)+'</li>'; }); H+='</ol></div>'; } out.innerHTML=H||'<div class="muted">Пусто, попробуй ещё раз.</div>'; }
function _x5copyBlock(label,txt){ if(!txt)return ''; return '<div class="fnl-copy"><div class="fc-lab">'+label+'</div><div class="fc-row"><div class="fc-tx">'+_x5esc(txt)+'</div><button class="pbtn sm" onclick="fnlCopy(this)" data-c="'+_x5esc(txt)+'">Копировать</button></div></div>'; }
function fnlCopy(btn){ try{ var t=btn.getAttribute('data-c')||''; _x5copy(btn,t); _x5toast('Скопировано','📋'); }catch(e){} }
function _x5snap(){ var s=_x5S(),c=s.channel||{},ai=s.ai||{}; var med=0; try{ if(s.groups)med=Math.round((s.groups.longs&&s.groups.longs.med)||(s.groups.shorts&&s.groups.shorts.med)||0); }catch(e){} var score=null; try{ if(ai.score!=null)score=Math.round(ai.score); else if(typeof getScore==='function')score=getScore(); }catch(e){} return { ts:Date.now(), score:score, subs:c.subs||0, videoCount:c.videoCount||0, totalViews:c.totalViews||0, med:med, vids:(s.videos&&s.videos.length)||0 }; }
function wkInit(){ var box=_x5id('wkDelta'); if(!box||!_x5S().channel)return; var key=_x5chKey(); var arr=_x5lget(key,[]); if(!Array.isArray(arr))arr=[]; var cur=_x5snap(); var last=arr.length?arr[arr.length-1]:null; if(!last||(cur.ts-last.ts)>12*3600*1000){ arr.push(cur); if(arr.length>14)arr=arr.slice(arr.length-14); } else { arr[arr.length-1]=cur; } _x5lset(key,arr); var base=null; for(var i=arr.length-2;i>=0;i--){ base=arr[i]; if((cur.ts-arr[i].ts)>=6.5*24*3600*1000)break; } if(arr.length<2||!base){ box.innerHTML='<div class="wk-first">📍 Это первый замер канала. Возвращайся через неделю, я сравню показатели и соберу план роста на основе динамики.</div>'; window.__x5base=null; window.__x5cur=cur; return; } window.__x5base=base; window.__x5cur=cur; box.innerHTML=_x5deltaHtml(base,cur); }
function _x5deltaHtml(b,c){ function row(label,bv,cv,goodUp){ var d=(cv||0)-(bv||0); var good=(d===0)?'wk-flat':(((d>0)===goodUp)?'wk-good':'wk-bad'); var arrow=d>0?'▲':(d<0?'▼':'—'); var ds=(d>0?'+':'')+_x5num(d); return '<div class="wk-metric '+good+'"><div class="wm-k">'+label+'</div><div class="wm-v">'+_x5num(cv)+'</div><div class="wm-d">'+arrow+' '+ds+'</div></div>'; } var days=Math.max(1,Math.round((c.ts-b.ts)/(24*3600*1000))); var H='<div class="wk-period">Сравнение с замером '+days+' дн. назад</div><div class="wk-grid">'; if(c.score!=null&&b.score!=null)H+=row('Индекс роста',b.score,c.score,true); H+=row('Подписчики',b.subs,c.subs,true); H+=row('Медиана просм/день',b.med,c.med,true); H+=row('Всего просмотров',b.totalViews,c.totalViews,true); H+='</div>'; return H; }
async function wkBuild(){ var out=_x5id('wkOut'); if(!out)return; if(!_x5S().channel){ out.innerHTML='<div class="muted">Сначала проанализируй канал на главном экране.</div>'; return; } out.innerHTML='<div class="x5-load"><span class="loader-ring"></span> Собираю разбор и план на неделю…</div>'; var b=window.__x5base,c=window.__x5cur||_x5snap(); var dyn=''; if(b&&c){ dyn='ДИНАМИКА за период:'+NL+'- Индекс роста: '+((b.score!=null&&c.score!=null)?(b.score+' -> '+c.score):'нет данных')+NL+'- Подписчики: '+b.subs+' -> '+c.subs+NL+'- Медиана просмотров в день: '+b.med+' -> '+c.med+NL; } else { dyn='Это первый замер, динамики пока нет, дай план роста на основе текущего состояния канала.'+NL; } var sys='Ты продюсер канала, ведёшь еженедельный разбор. Отвечай ТОЛЬКО валидным JSON без markdown. Структура: {"verdict":"1-2 предложения: что происходит с каналом и на чём сфокусироваться на этой неделе","focus":[{"title":"фокус-задача недели","why":"почему важно именно сейчас","how":"как сделать конкретно"}],"checklist":["короткое конкретное действие"]}. Поле focus: ровно 3 пункта, привязаны к динамике и главной утечке роста. Поле checklist: 5-7 коротких конкретных задач на неделю. По-русски, без воды.'; var user='Сделай недельный разбор и план.'+NL+'КОНТЕКСТ КАНАЛА:'+NL+_x5ctx()+NL+NL+dyn; try{ var kb=(typeof kbFor==='function')?kbFor('idea'):''; var d=await callMistralRaw(sys+(kb?(NL+NL+kb):''), user, 1700); _x5renderWeek(d); }catch(e){ out.innerHTML='<div class="muted">Не удалось собрать план, попробуй ещё раз через пару секунд.</div>'; } }
function _x5renderWeek(d){ var out=_x5id('wkOut'); if(!out)return; d=d||{}; var H=''; if(d.verdict)H+='<div class="wk-verdict">'+_x5esc(d.verdict)+'</div>'; if(Array.isArray(d.focus)&&d.focus.length){ H+='<div class="wk-focus">'; d.focus.forEach(function(f,i){ f=f||{}; H+='<div class="wk-fcard"><div class="wf-n">'+(i+1)+'</div><div class="wf-b"><div class="wf-t">'+_x5esc(f.title||'')+'</div><div class="wf-y">'+_x5esc(f.why||'')+'</div><div class="wf-h">'+_x5esc(f.how||'')+'</div></div></div>'; }); H+='</div>'; } if(Array.isArray(d.checklist)&&d.checklist.length){ H+='<div class="fnl-block"><div class="fb-h">✅ Чек-лист недели</div><div class="wk-checks">'; d.checklist.forEach(function(t){ H+='<label class="wk-chk"><input type="checkbox"/> <span>'+_x5esc(t)+'</span></label>'; }); H+='</div></div>'; } out.innerHTML=H||'<div class="muted">Пусто, попробуй ещё раз.</div>'; }
(function(){var prev=window.__vioraExtra;window.__vioraExtra=function(c){if(typeof prev==='function'){try{prev(c);}catch(e){}}try{wkInit();}catch(e){}};})();
